spring.application.name=weather-insights
spring.datasource.url=jdbc:postgresql://localhost:5432/weather
spring.datasource.username=weather
spring.datasource.password=weather
spring.jpa.hibernate.ddl-auto=update
spring.data.redis.host=localhost
spring.data.redis.port=6379